### ISSUE TITLE
Move the domain loader into domainModel.py and update it so it loads tags fully.

### ISSUE THREAD

**Issue by DubThink** [tobydragon/GameShell#15]
Currently, our domain .csv's have a header row which labels each column's role. We should use these as the tag types (i.e. the key for the `.tags` dict) The notable exceptions are:
1.  "name": goes into the name field
2. "image path": goes into the image path field
3. "description": goes into the description field (proposed)

**Comment by tobydragon** [comment]
add documentation, particularly for constructor

**Comment by DubThink** [comment]
added documentation
