### ISSUE TITLE
Card class

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/GameShell#19]
Card

DATA
selectionBorderColor
pygbutton
individual

mainArea
captionArea

OPERATIONS
display
setSelected(Enum right, wrong, etc.)
flip

**Comment by DubThink** [comment]
We can use {} style string formatting, so that in the title and description field, we'll automatically use the tags of the individual.
`titleText=title.format(individual.tags)` should do it.
Similarly for the description field.

**Comment by DubThink** [comment]
Formatting for the title field is implemented. The caption area hasn't been added at all yet.

**Comment by DubThink** [comment]
As I finish up integrating Cards into stageView, I need to better figure out what functionality belongs where.

-stageModel vs stageView.
-how stageView should be initialized.

At the current moment, a new stageView is created for every stageModel. Is this how it should work?

**Comment by tobydragon** [comment]
make entire card clickable

**Comment by DubThink** [comment]
I propose we close this issue and open new ones for each feature/change.

**Comment by tobydragon** [comment]
Turn comments into new issues where necessary
