### ISSUE TITLE
Check/add the ability to use tags with  commas

### ISSUE THREAD

**Issue by DubThink** [tobydragon/GameShell#23]
The csv format supports fields with commas by wrapping them in quotes. We may need to strip these while importing.

**Comment by tobydragon** [comment]
look for .csv processing package for python

**Comment by DubThink** [comment]
Fixed in 7bdf4e12b805322b6c24fe54115f925bb4ba2ef6; Now using csv library. This also lets us have multiple tags of the same tag type.
