### ISSUE TITLE
Add answer logging system to new controller/game system

### ISSUE THREAD

**Issue by DubThink** [tobydragon/GameShell#30]

**Comment by tobydragon** [comment]
action logging rather than answer logging

**Comment by DubThink** [comment]
This is mainly waiting on me figuring out xml in python. [Here](https://docs.python.org/3/library/xml.etree.elementtree.html) is the doc page for the library. I mostly need a better understanding of how xml files work.

**Comment by DubThink** [comment]
This is now mostly implemented. We can log both card selections/deselections and stage evaluations.
